[project]
name = "taxi-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=6.0.0",
    "dlt>=1.22.0",
    "duckdb>=1.4.4",
    "pip>=26.0.1",
]
